import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Check, Clock3, FileText, RotateCcw, Save, ShieldCheck, Trash2, TrendingDown, TrendingUp } from "lucide-react";
import { getUserProfile } from "../firebase/userService";
import { getAllSchemes } from "../firebase/schemeService";
import { getChannelPartners } from "../firebase/partnerService";
import { generateSchemeRecommendations } from "../firebase/recommendationService";
import { deleteDigitalTwinScenario, getDigitalTwinScenarios, saveDigitalTwinScenario } from "../firebase/digitalTwinService";
import demoSchemes from "../data/schemes";
import demoPartners from "../data/partners";
import { calculateApplicationReadiness, calculateDocumentReadiness, compareRecommendations, getDocumentsForScheme, getScenarioMetrics } from "../utils/digitalTwin";

const money = (value) => `₹${Math.round(Number(value) || 0).toLocaleString("en-IN")}`;
const ageFrom = (value) => { const date = new Date(value); if (!value || Number.isNaN(date.getTime())) return 30; const today = new Date(); return Math.max(0, today.getFullYear() - date.getFullYear() - ((today.getMonth() < date.getMonth() || (today.getMonth() === date.getMonth() && today.getDate() < date.getDate())) ? 1 : 0)); };

function DigitalTwin({ user }) {
  const [profile, setProfile] = useState({});
  const [schemes, setSchemes] = useState([]);
  const [partners, setPartners] = useState([]);
  const [history, setHistory] = useState([]);
  const [scenario, setScenario] = useState(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [saveMessage, setSaveMessage] = useState("");

  useEffect(() => {
    let mounted = true;
    Promise.all([getUserProfile(user?.uid).catch(() => null), getAllSchemes().catch(() => []), getChannelPartners().catch(() => []), getDigitalTwinScenarios(user?.uid).catch(() => [])])
      .then(([loadedProfile, loadedSchemes, loadedPartners, loadedHistory]) => {
        if (!mounted) return;
        const nextProfile = loadedProfile || {};
        const nextSchemes = loadedSchemes.length ? loadedSchemes : demoSchemes;
        setProfile(nextProfile); setSchemes(nextSchemes); setPartners(loadedPartners.length ? loadedPartners : demoPartners); setHistory(loadedHistory);
        const bestRate = Number(nextSchemes.find((scheme) => Number(scheme.interestRate) > 0)?.interestRate || 9);
        const cost = Number(nextProfile.projectCost || 500000);
        setScenario({ projectCost: cost, requiredLoan: Number(nextProfile.requiredLoan || Math.round(cost * 0.75)), tenureYears: Number(nextProfile.tenureYears || 5), interestRate: Number(nextProfile.interestRate || bestRate), monthlyIncome: Number(nextProfile.monthlyIncome || (Number(nextProfile.annualIncome || 0) / 12) || 25000) });
      })
      .catch(() => mounted && setError("Unable to load your Digital Twin data. You can still review it after refreshing."))
      .finally(() => mounted && setLoading(false));
    return () => { mounted = false; };
  }, [user?.uid]);

  const applicant = useMemo(() => ({ age: ageFrom(profile.dateOfBirth), income: Number(profile.annualIncome || 0), category: profile.category || "General", education: profile.education || "", state: profile.state || "", occupation: profile.occupation || "" }), [profile]);
  const projectType = profile.businessType || profile.projectType || profile.occupation || "Services";
  const purpose = profile.purpose || "business";
  const original = useMemo(() => ({ projectCost: Number(profile.projectCost || scenario?.projectCost || 0), requiredLoan: Number(profile.requiredLoan || scenario?.requiredLoan || 0), tenureYears: Number(profile.tenureYears || scenario?.tenureYears || 5), interestRate: Number(profile.interestRate || scenario?.interestRate || 9), monthlyIncome: Number(profile.monthlyIncome || (Number(profile.annualIncome || 0) / 12) || scenario?.monthlyIncome || 0) }), [profile, scenario]);
  const originalRecommendations = useMemo(() => generateSchemeRecommendations(applicant, { projectType, projectCost: original.projectCost, requiredLoan: original.requiredLoan, purpose }, schemes), [applicant, original, projectType, purpose, schemes]);
  const simulatedRecommendations = useMemo(() => scenario ? generateSchemeRecommendations(applicant, { projectType, projectCost: scenario.projectCost, requiredLoan: scenario.requiredLoan, purpose }, schemes) : [], [applicant, projectType, purpose, scenario, schemes]);
  const currentMetrics = useMemo(() => getScenarioMetrics(original), [original]);
  const simulatedMetrics = useMemo(() => getScenarioMetrics(scenario || original), [scenario, original]);
  const selectedScheme = simulatedRecommendations[0] || originalRecommendations[0];
  const documents = useMemo(() => getDocumentsForScheme(selectedScheme, profile), [profile, selectedScheme]);
  const documentReadiness = useMemo(() => calculateDocumentReadiness(documents), [documents]);
  const readiness = useMemo(() => calculateApplicationReadiness({ profile, financial: simulatedMetrics, documentReadiness, schemeResults: simulatedRecommendations }), [documentReadiness, profile, simulatedMetrics, simulatedRecommendations]);
  const changes = compareRecommendations(originalRecommendations.filter((item) => item.score > 0), simulatedRecommendations.filter((item) => item.score > 0));

  const updateScenario = (event) => setScenario((current) => ({ ...current, [event.target.name]: Number(event.target.value) }));
  const reset = () => setScenario({ ...original });
  const partnerFor = (recommendations) => {
    const schemeId = recommendations[0]?.id;
    return [...partners].map((partner) => ({ ...partner, match: (partner.schemesSupported?.includes(schemeId) ? 55 : 20) + ((partner.state || "").toLowerCase() === (profile.state || "").toLowerCase() ? 25 : 0) + (partner.distance ? Math.max(0, 20 - Number.parseFloat(partner.distance)) : 10) })).sort((a, b) => b.match - a.match)[0];
  };
  const currentPartner = partnerFor(originalRecommendations); const simulatedPartner = partnerFor(simulatedRecommendations);
  const save = async () => { setSaving(true); setSaveMessage(""); try { const saved = await saveDigitalTwinScenario(user.uid, { name: `${projectType} plan`, originalScenario: original, simulatedScenario: scenario, recommendationResults: { original: originalRecommendations.slice(0, 5), simulated: simulatedRecommendations.slice(0, 5) }, financialResults: { current: currentMetrics, simulated: simulatedMetrics }, documentReadiness, applicationReadiness: readiness }); setHistory((current) => [saved, ...current]); setSaveMessage("Scenario saved without changing your profile."); } catch (saveError) { setSaveMessage(saveError.message); } finally { setSaving(false); } };
  const remove = async (id) => { try { await deleteDigitalTwinScenario(user.uid, id); setHistory((current) => current.filter((item) => item.id !== id)); } catch (deleteError) { setSaveMessage(deleteError.message); } };

  if (loading) return <div className="empty-result page-skeleton"><div className="skeleton-orb" /><h2>Building your Digital Twin...</h2></div>;
  if (error) return <div className="empty-result"><ShieldCheck size={34} /><h2>Digital Twin unavailable</h2><p>{error}</p></div>;
  if (!scenario) return <div className="empty-result"><h2>Complete your profile to simulate a plan</h2><p>We need a few financial inputs before we can model your scenario.</p></div>;

  const metricChange = (label, current, next, format = (value) => value) => <div className="twin-change"><span>{label}</span><strong>{format(current)}</strong><ArrowDown size={15} /><strong>{format(next)}</strong><small className={next <= current ? "change-good" : "change-bad"}>{next <= current ? <TrendingDown size={14} /> : <TrendingUp size={14} />}{format(Math.abs(next - current))} change</small></div>;
  return <div className="twin-page">
    <div className="page-heading animate-in"><p className="eyebrow">SCHEME SATHI DIGITAL TWIN</p><h1>Your plan, in motion</h1><p>A transparent financial scenario based on your profile. Simulation changes stay local until you save them.</p></div>
    <div className="twin-grid">
      <section className="twin-panel twin-profile"><div className="panel-heading"><div><p className="eyebrow">PROFILE SUMMARY</p><h2>{profile.name || user.displayName || "Your entrepreneur profile"}</h2></div><ShieldCheck size={22} /></div><div className="profile-facts"><div><span>Age</span><strong>{applicant.age} years</strong></div><div><span>Category</span><strong>{profile.category || "Not provided"}</strong></div><div><span>State</span><strong>{profile.state || "Not provided"}</strong></div><div><span>Occupation</span><strong>{profile.occupation || "Not provided"}</strong></div><div><span>Annual income</span><strong>{money(profile.annualIncome)}</strong></div><div><span>Business type</span><strong>{projectType}</strong></div></div></section>
      <section className="twin-panel scenario-card"><div className="panel-heading"><div><p className="eyebrow">CURRENT FINANCIAL SCENARIO</p><h2>Planning risk, not a credit score</h2></div><span className={`risk-badge ${currentMetrics.risk.tone}`}>{currentMetrics.risk.label}</span></div><div className="scenario-metrics"><div><span>Project cost</span><strong>{money(original.projectCost)}</strong></div><div><span>Required loan</span><strong>{money(original.requiredLoan)}</strong></div><div><span>Estimated EMI</span><strong>{money(currentMetrics.emi)}</strong></div><div><span>Monthly income</span><strong>{money(original.monthlyIncome)}</strong></div><div><span>EMI burden</span><strong>{currentMetrics.ratio.toFixed(0)}%</strong></div></div><p className="muted-note">Financial Planning Risk Indicator: estimated from EMI-to-income burden. Verify lending terms with the authorized channel partner.</p></section>
    </div>
    <section className="twin-panel twin-simulator"><div className="panel-heading"><div><p className="eyebrow">WHAT IF SIMULATOR</p><h2>Change the business plan</h2></div><button className="secondary-button" onClick={reset}><RotateCcw size={15} /> Reset</button></div><div className="control-grid">{[["projectCost","Project cost",10000,5000000],["requiredLoan","Required loan",0,5000000],["tenureYears","Loan tenure (years)",1,15],["interestRate","Estimated interest rate (%)",1,20],["monthlyIncome","Expected monthly income",0,500000]].map(([name, label, min, max]) => <label className="twin-control" key={name}><span>{label}</span><div className="control-values"><small>Current {name === "interestRate" ? `${original[name]}%` : name === "tenureYears" ? `${original[name]} yrs` : money(original[name])}</small><strong>{name === "interestRate" ? `${scenario[name]}%` : name === "tenureYears" ? `${scenario[name]} yrs` : money(scenario[name])}</strong></div><input type="range" name={name} min={min} max={max} step={name === "interestRate" ? 0.1 : name === "tenureYears" ? 1 : 10000} value={scenario[name]} onChange={updateScenario} /><input className="compact-number" type="number" name={name} min={min} max={max} value={scenario[name]} onChange={updateScenario} /></label>)}</div></section>
    <section className="twin-panel"><div className="panel-heading"><div><p className="eyebrow">WHAT CHANGED?</p><h2>Current plan versus simulation</h2></div><span className="simulated-label">SIMULATED</span></div><div className="change-grid">{metricChange("Estimated EMI", currentMetrics.emi, simulatedMetrics.emi, money)}{metricChange("EMI burden", currentMetrics.ratio, simulatedMetrics.ratio, (value) => `${Number(value).toFixed(0)}%`)}<div className="twin-change"><span>Financial risk</span><strong>{currentMetrics.risk.label}</strong><ArrowDown size={15} /><strong>{simulatedMetrics.risk.label}</strong><small>{simulatedMetrics.risk.label === currentMetrics.risk.label ? "No band change" : "Review affordability before applying"}</small></div></div></section>
    <section className="twin-panel"><div className="panel-heading"><div><p className="eyebrow">SCHEME IMPACT</p><h2>Recommendation movement</h2></div><span>{simulatedRecommendations.length} considered</span></div><div className="impact-columns"><div><h3>Original plan</h3><strong>{originalRecommendations.length}</strong><p>schemes considered</p><small>Best match: {originalRecommendations[0]?.name || "None"} ({originalRecommendations[0]?.score || 0}%)</small></div><div><h3>Simulated plan</h3><strong>{simulatedRecommendations.length}</strong><p>schemes considered</p><small>Best match: {simulatedRecommendations[0]?.name || "None"} ({simulatedRecommendations[0]?.score || 0}%)</small></div></div><div className="impact-result"><span><ArrowUp size={15} /> {changes.unlocked.length} potentially unlocked</span><span><ArrowDown size={15} /> {changes.lost.length} no longer suitable</span></div></section>
    <div className="twin-grid"><section className="twin-panel"><div className="panel-heading"><div><p className="eyebrow">DOCUMENT READINESS</p><h2>{documentReadiness.percentage}% complete</h2></div><FileText size={22} /></div><div className="readiness-bar"><span style={{ width: `${documentReadiness.percentage}%` }} /></div><p>{documentReadiness.completed} of {documentReadiness.total} required documents available</p><div className="document-list">{documents.map((document) => <div className="document-row" key={document.id}><span className={`document-icon ${document.status}`}><Check size={14} /></span><div><strong>{document.name}</strong><small>{document.status === "available" ? "Available" : document.status === "pending" ? "Pending verification" : "Missing"} · {document.category || "SCHEME-SPECIFIC"}</small></div></div>)}</div><p className="muted-note">Commonly required documents — verify exact requirements with the authorized channel partner.</p></section>
      <section className="twin-panel"><div className="panel-heading"><div><p className="eyebrow">APPLICATION READINESS</p><h2>{readiness.total} / 100</h2></div><Clock3 size={22} /></div><p>Scheme Sathi Estimated Application Readiness</p><div className="readiness-breakdown"><span>Profile completeness <b>{readiness.profileScore}/25</b></span><span>Financial readiness <b>{readiness.financialScore}/25</b></span><span>Document readiness <b>{readiness.documentScore}/30</b></span><span>Scheme compatibility <b>{readiness.schemeScore}/20</b></span></div><h3 className="subheading">Document pathway</h3><div className="pathway"><span><b>1</b> Identity documents <em>{documents.filter((item) => item.category === "IDENTITY" && item.status === "available").length ? "Complete" : "Action needed"}</em></span><span><b>2</b> Financial documents <em>{documentReadiness.missing ? `${documentReadiness.missing} missing` : "Complete"}</em></span><span><b>3</b> Business proposal <em>Recommended</em></span><span><b>4</b> Partner review <em>{documentReadiness.missing ? "Locked until required documents complete" : "Ready to discuss"}</em></span></div></section></div>
    <section className="twin-panel"><div className="panel-heading"><div><p className="eyebrow">YOUR PLAN IMPACT</p><h2>Practical next steps</h2></div><TrendingUp size={22} /></div><div className="suggestion-list"><p>{simulatedMetrics.emi <= currentMetrics.emi ? "Lower estimated EMI improves the monthly plan." : "Higher estimated EMI increases the monthly burden; review the amount or tenure."}</p><p>{simulatedMetrics.ratio <= 45 ? "The simulated burden is within the lower planning bands." : "Consider reducing the loan or increasing expected income before approaching a partner."}</p><p>{documentReadiness.missing ? `Complete ${documentReadiness.missing} required document${documentReadiness.missing > 1 ? "s" : ""} to improve readiness.` : "Required document checklist is complete for this analysis."}</p></div></section>
    <div className="twin-grid"><section className="twin-panel partner-impact"><div className="panel-heading"><div><p className="eyebrow">SMART PARTNER IMPACT</p><h2>Who can help next</h2></div></div><div className="partner-compare"><div><span>Current plan</span><strong>{currentPartner?.name || "No partner data"}</strong><small>{currentPartner ? `${currentPartner.match}% planning match` : "Verify availability locally"}</small></div><div><span>Simulated plan</span><strong>{simulatedPartner?.name || "No partner data"}</strong><small>{simulatedPartner ? `${simulatedPartner.match}% planning match` : "Verify availability locally"}</small></div></div><p className="muted-note">Partner fit is an estimate using scheme support, state, and listed distance. It is not an approval or availability guarantee.</p></section><section className="twin-panel"><div className="panel-heading"><div><p className="eyebrow">SCENARIO HISTORY</p><h2>Saved plans</h2></div><button className="primary-button" onClick={save} disabled={saving}><Save size={15} /> {saving ? "Saving..." : "Save scenario"}</button></div>{saveMessage && <p className="inline-feedback">{saveMessage}</p>}{history.length ? <div className="history-list">{history.slice(0, 4).map((item) => <div className="history-row" key={item.id}><div><strong>{item.name || "Saved scenario"}</strong><small>Loan {money(item.simulatedScenario?.requiredLoan)} · Readiness {item.applicationReadiness?.total || 0}/100</small></div><div className="history-actions"><button className="secondary-button" onClick={() => { setScenario({ ...item.simulatedScenario }); setSaveMessage(`${item.name || "Scenario"} loaded for comparison.`); }}>Load</button><button className="icon-button" aria-label={`Delete ${item.name || "scenario"}`} onClick={() => remove(item.id)}><Trash2 size={15} /></button></div></div>)}</div> : <p className="muted-note">No saved scenarios yet.</p>}</section></div>
  </div>;
}

export default DigitalTwin;
